/**
 * Mã lỗi nghiệp vụ (Business Error Codes) độc lập với mã trạng thái HTTP. Phân nhóm rõ ràng theo tiền tố (Prefix) để Mobile Apps/Web Frontend bắt mã lỗi quốc tế hóa (i18n) dễ dàng
 * 
 * */

export enum SystemErrorCode {
  // --- 1. NHÓM XÁC THỰC & PHÂN QUYỀN (AUTH_*) ---[cite: 1]
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_FORBIDDEN_RESOURCE = 'AUTH_FORBIDDEN_RESOURCE',
  AUTH_TENANT_MISMATCH = 'AUTH_TENANT_MISMATCH',
  AUTH_CREDENTIALS_INVALID = 'AUTH_CREDENTIALS_INVALID',
  AUTH_SESSION_REVOKED = 'AUTH_SESSION_REVOKED',

  // --- 2. NHÓM XÁC THỰC DỮ LIỆU ĐẦU VÀO (REQ_*) ---[cite: 1]
  REQ_VALIDATION_ERROR = 'REQ_VALIDATION_ERROR',
  REQ_MALFORMED_PAYLOAD = 'REQ_MALFORMED_PAYLOAD',
  REQ_MISSING_IDEMPOTENCY_KEY = 'REQ_MISSING_IDEMPOTENCY_KEY',
  REQ_IDEMPOTENCY_PAYLOAD_MISMATCH = 'REQ_IDEMPOTENCY_PAYLOAD_MISMATCH',
  REQ_INVALID_UUID = 'REQ_INVALID_UUID',
  REQ_INVALID_DATE_RANGE = 'REQ_INVALID_DATE_RANGE',
  REQ_TIMEOUT = 'REQ_TIMEOUT',
  REQ_PAYLOAD_TOO_LARGE = 'REQ_PAYLOAD_TOO_LARGE',

  // --- 3. NHÓM TRẠNG THÁI TÀI NGUYÊN & ĐỒNG THỜI (RES_*) ---[cite: 1]
  RES_NOT_FOUND = 'RES_NOT_FOUND',
  RES_ALREADY_EXISTS = 'RES_ALREADY_EXISTS',
  RES_CONFLICT = 'RES_CONFLICT',
  RES_CONCURRENCY_CONFLICT = 'RES_CONCURRENCY_CONFLICT', // Optimistic Lock (@VersionColumn)
  RES_LOCKED = 'RES_LOCKED',                             // Đang bị giữ bởi Distributed Lock[cite: 1]
  RES_FEATURE_DISABLED = 'RES_FEATURE_DISABLED',         // Tính năng đang tắt bởi Feature Flag

  // --- 4. NHÓM NGHIỆP VỤ ĐẶT VÉ & THANH TOÁN (BIZ_*) ---[cite: 1]
  BIZ_FLIGHT_SEAT_UNAVAILABLE = 'BIZ_FLIGHT_SEAT_UNAVAILABLE',
  BIZ_PRICE_MISMATCH = 'BIZ_PRICE_MISMATCH',
  BIZ_BOOKING_EXPIRED = 'BIZ_BOOKING_EXPIRED',
  BIZ_PAYMENT_FAILED = 'BIZ_PAYMENT_FAILED',
  BIZ_PAYMENT_ALREADY_SETTLED = 'BIZ_PAYMENT_ALREADY_SETTLED',

  // --- 5. NHÓM BẢO MẬT & GIỚI HẠN LƯU LƯỢNG (SEC_*) ---[cite: 1]
  SEC_RATE_LIMIT_EXCEEDED = 'SEC_RATE_LIMIT_EXCEEDED',
  SEC_CORS_VIOLATION = 'SEC_CORS_VIOLATION',
  SEC_DECRYPTION_FAILED = 'SEC_DECRYPTION_FAILED',

  // --- 6. NHÓM TÍCH HỢP NGOẠI VI & HẠ TẦNG (EXT_*, SYS_*) ---[cite: 1]
  EXT_PARTNER_TIMEOUT = 'EXT_PARTNER_TIMEOUT',
  EXT_CIRCUIT_BREAKER_OPEN = 'EXT_CIRCUIT_OPEN',
  EXT_BULKHEAD_LIMIT_REACHED = 'EXT_BULKHEAD_LIMIT_REACHED',
  SYS_INTERNAL_ERROR = 'SYS_INTERNAL_ERROR',
  SYS_DATABASE_ERROR = 'SYS_DATABASE_ERROR',
  SYS_SERVICE_UNAVAILABLE = 'SYS_SERVICE_UNAVAILABLE',
}